# -*- coding: utf-8 -*-
"""graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8UtDu8qHbuGgW9t8ooM9cxZBu0BWlzv
"""

import json
from google.colab import files
uploaded = files.upload()

uploaded
import io
file_name = "cacheIMDB_TOP750.json"
io.StringIO(file_name)
imdb = json.loads(uploaded[file_name].decode("utf-8"))

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.DataFrame(imdb.values())
df

df['Country']

# df_country = df[(df['Country'] != float(np.nan))]
df['Country'].fillna('Others', inplace=True)
df_country = df.drop(df[df['Country'] == 'Others'].index)
df_country['Country'] = df_country['Country'].str.split(', ')
df_country = df_country.explode('Country', ignore_index=True)
country_list = df_country['Country'].value_counts().rename_axis('Country').reset_index(name='counts')
country_list.plot.bar(x="Country", y="counts", figsize=(25, 8))

df['imdbRating'].fillna('Others', inplace=True)
df_imdbRating = df.drop(df[df['imdbRating'] == 'N/A'].index)
df_imdbRating2 = df_imdbRating.drop(df[df['imdbRating'] == 'Others'].index)
len(df_imdbRating2)
df_imdbRating2['imdbRating'].value_counts()
df_imdbRating2['imdbRating'] = pd.to_numeric(df_imdbRating2['imdbRating'])
bins = pd.IntervalIndex.from_tuples([(0, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)])
df_imdbRating2['imdbRating'] = pd.cut(df_imdbRating2['imdbRating'], bins).astype(str).str.replace('(', '').str.replace(']', '').str.replace(',', ' -')
df_imdbRating2['imdbRating']

df_imdbRating2.groupby('imdbRating').size().plot(kind='pie', ylabel ='')

#pairplot imdbVotes & imdbRating
# df['imdbVotes']
# for i in df['imdbVotes']:
  # print (i)
df['imdbVotes'].fillna('Others', inplace=True)
df_rel_Votes_Rating = df.drop(df[df['imdbVotes'] == 'N/A'].index)
df_rel_Votes_Rating = df_rel_Votes_Rating.drop((df[df['imdbVotes'] == 'Others'].index))
# for i in df_rel_Votes_Rating['imdbVotes']:
#   print(i)
# len(df_rel_Votes_Rating)
df_rel_Votes_Rating['imdbVotes'] = df_rel_Votes_Rating['imdbVotes'].str.replace(',','').astype(int)
# for i in df_rel_Votes_Rating['imdbVotes']:
#   print(type(i))
# len(df_rel_Votes_Rating)
df['imdbRating'].fillna('Others', inplace=True)
df_rel_Votes_Rating = df_rel_Votes_Rating.drop(df_rel_Votes_Rating[df_rel_Votes_Rating['imdbRating'] == 'N/A'].index)
df_rel_Votes_Rating = df_rel_Votes_Rating.drop((df_rel_Votes_Rating[df_rel_Votes_Rating['imdbRating'] == 'Others'].index))
df_rel_Votes_Rating['imdbRating'] = df_rel_Votes_Rating['imdbRating'].astype(float)
# len(df_rel_Votes_Rating)


sns.pairplot(data=df_rel_Votes_Rating, vars=['imdbVotes','imdbRating'])

#relplot Year with imdbRating

# df_rel_Votes_Rating['Year']
# for i in df_rel_Votes_Rating['Year']:
#   print(i)


# df_rel_Votes_Rating['Year'] = df_rel_Votes_Rating['Year'].str.slice(stop=4).astype(int)
# for i in df_rel_Votes_Rating['Year']:
#   print(type(i))
# df_rel_Votes_Rating['Year'] = df_rel_Votes_Rating['Year']
# for i in df_rel_Votes_Rating['Year']:
#   print(type(i))

sns.relplot(data=df_rel_Votes_Rating, x="Year", y="imdbRating")